### ISSUE TITLE
Decidir grade do curso de lógica

### ISSUE THREAD

**Issue by larismourullo** [openschoolbr/curso-logica-programacao#1]
Então como foi dito no grupo do telegram tenho uma ementa de lógica de programação e um conteúdo pronto que só necessitaria de algumas alterações para ser lançado como um curso. Estou pondo aqui esta ementa e se iremos mesmo separar ela para os cursos de Lógica de Programação, Estrutura de Dados e Algoritmo. Abaixo se encontra os tópicos que seriam abordados:

1. INTRODUÇÃO À LÓGICA DE PROGRAMAÇÃO
1.1. O QUE É UM ALGORITMO?
1.2. IMPORT NCIA DE CONSTRUIR UM ALGORITMO
2. TÓPICOS PRELIMINARES
2.1. TIPOS PRIMITIVOS
2.2. CONSTANTES
2.3. VARIÁVEL
2.3.1. FORMAÇÃO DE IDENTIFICADORES
2.3.1. DECLARAÇÃO DE VARIÁVEIS
2.4. EXPRESSÕES ARITMÉTICAS
2.4.1. OPERADORES ARITMÉTICOS
2.4.2. PRIORIDADES
2.5. EXPRESSÕES LÓGICAS
2.5.1. OPERADORES RELACIONAIS
2.5.2. OPERADORES LÓGICOS
2.5.3. TABELAS-VERDADE
2.5.4. PRIORIDADES
2.6. COMANDO DE ATRIBUIÇÃO
2.7. COMANDO DE ENTRADA E SAÍDA
2.7.1. ENTRADA DE DADOS
2.7.2. SAÍDA DE DADOS
2.8. BLOCOS
3. ESTRUTURAS DE CONTROLE
3.1. ESTRUTURA SEQUENCIAL
3.2. ESTRUTURA DE SELEÇÃO
3.2.1. SELEÇÃO SIMPLES
3.2.2. SELEÇÃO COMPOSTA
3.2.3. SELEÇÃO ENCADEADA
3.2.3.1. SELEÇÃO ENCADEADA HETEROGÊNEA
3.2.3.2. SELEÇÃO ENCADEADA HOMOGÊNEA
3.3. ESTRUTURA DE REPETIÇÃO
3.3.1. REPETIÇÃO COM TESTE NO INÍCIO
3.3.2. REPETIÇÃO COM TESTE NO FINAL
3.3.3. REPETIÇÃO COM VARIÁVEL DE CONTROLE
3.3.4. COMPARAÇÃO ENTRE ESTRUTURAS DE REPETIÇÃO
4. ESTRUTURA DE DADOS
4.1. VARIÁVEIS COMPOSTAS HOMOGÊNEAS
4.1.1. VARIÁVEIS COMPOSTAS UNIDIMENSIONAIS
4.1.1.1. DECLARAÇÃO
4.1.1.2. MANIPULAÇÃO
4.1.2. VARIÁVEIS COMPOSTAS MULTIDIMENSIONAIS
4.1.2.1. DECLARAÇÃO
4.1.2.2. MANIPULAÇÃO
4.2. VARIÁVEIS COMPOSTAS HETEROGÊNEAS
4.2.1. REGISTROS
4.2.1.1. DECLARAÇÃO
4.2.1.2. MANIPULAÇÃO
4.2.2. REGISTROS DE CONJUNTO
4.2.2.1. DECLARAÇÃO
4.2.1.2. MANIPULAÇÃO
4.2.3. CONJUNTO DE REGISTROS
4.2.3.1. DECLARAÇÃO
4.2.2.2. MANIPULAÇÃO
5. ARQUIVOS
5.1. DECLARAÇÃO
5.2. MANIPULAÇÃO
5.2.1. ABRINDO UM ARQUIVO
5.2.2. FECHANDO UM ARQUIVO
5.2.3. COPIANDO UM REGISTRO
5.2.4. GUARDANDO UM REGISTRO
5.2.5. ELIMINANDO UM REGISTRO
5.2.6. CONCEPÇÃO SEQUENCIAL
5.2.7. CONCEPÇÃO DIRETA
5.3. ESTUDO DE CONCEPÇÕES
5.3.1. ARQUIVO DIRETO ACESSADO
5.3.2. ARQUIVO SEQUENCIAL ACESSADO RANDOMICAMENTE: ARQUIVOS INDEXADOS
6. MODULARIZANDO ALGORITMOS
6.1. DECOMPOSIÇÃO
6.2. MÓDULOS
6.2.1. DECLARAÇÃO
6.2.2. MANIPULAÇÃO
6.3. ESCOPO DE VARIÁVEIS
6.4. ESCOPO DE VARIÁVEIS
6.4.1. DECLARAÇÃO
6.4.2. MANIPULAÇÃO
6.5. CONTEXTO DE MÓDULOS
6.5.1. CONTEXTO DE AÇÃO
6.5.2. CONTEXTO DE RESULTADO
7. ESTRUTURA DE DADOS AVANÇADAS
7.1. LISTAS
7.1.1. DECLARAÇÃO
7.1.2. MANIPULAÇÃO
7.1.2.1. INSERÇÃO
7.1.2.2. REMOÇÃO
7.2. FILAS
7.2.1. DECLARAÇÃO
7.2.2. MANIPULAÇÃO
7.2.2.1. INSERÇÃO
7.2.2.2. REMOÇÃO
7.3. PILHAS
7.3.1. DECLARAÇÃO
7.3.2. MANIPULAÇÃO
7.3.2.1. INSERÇÃO
7.3.2.2. REMOÇÃO
7.4. ÁRVORES
7.4.1. DECLARAÇÃO
7.4.2. MANIPULAÇÃO
7.5. OUTRAS ESTRUTURAS
7.5.1. LISTAS DUPLAMENTE ENCADEADAS
7.5.2. LISTAS CIRCULARES
7.5.3. GRAFOS

Caso queiram ver o conteúdo basta acessar: https://docs.google.com/document/d/1vqFqfibIjPGSLEFAgPJmR1daS6JpsXceKIJ_qbFUdo0/edit?usp=sharing

**Comment by houstondapaz** [comment]
Que super conteúdo, parabéns! Vou dar uma lida.
Difícil é transformar esse conteúdo em um curso

**Comment by erandirjunior** [comment]
Ordenação?

**Comment by erandirjunior** [comment]
Busca

**Comment by houstondapaz** [comment]
Eu acho que esse é um dos cursos mais difíceis de ser criado, pois é a porta de entrada pro mundo das drogas... opa quer dizer programação, logo é pra uma galera que não tem uma base do que vai encontrar pela frente, então temos que pensar muito bem na dinâmica dele.
Dei uma lida por cima no conteúdo da @larismourullo e ele aborda a grande maioria de assuntos que precisam ser absorvidos por qlqr um que quer aprender uma linguagem de programação.
Mas eu entendi o que está escrito ali pq eu já sei, mas como passar isso para alguem leigo no assunto?
Isso é matéria de faculdade, uns 2 semestres se não me engano.
Acho que temos que pegar esse conteudo e nos focarmos em como criar a didatica dele...
Ideias...

**Comment by larismourullo** [comment]
@houstondapaz por isso mesmo eu acredito que seja necessário alterar algumas coisas, eu sempre tento contextualizar com coisas do nosso dia-a-dia pra explicar algo pra alguém, ou traduzir algum termo tipo, pensa no IF como SE, se fiz algo vai te retornar algo, se você for bom, você ganha presente do papai noel. Coisas bobas assim, mas que facilitam bastante no entendimento e faz a pessoa sempre lembrar por ser fácil. A questão é alterar o conteúdo pra isso. E ao meu ver fica muito extenso esse conteúdo todo pra lógica. Pensei em pegar os dois últimos capítulo e fechar um pra um curso só de algoritmo e outro apenas só pra estruturação de dados por ser mais complexo ao meu ver.

**Comment by larismourullo** [comment]
@houstondapaz ao rever agora vejo que o capítulo 5 (arquivos) da uma introdução a CRUD que poderia ser abordado também no curso de algoritmo em vez de algo pra lógica. E só pra deixar aqui, uns 90% do conteúdo desse resumo eu retirei de um livro de lógica de programação, então se utilizarmos algo dele acho que devemos por como citação.

**Comment by houstondapaz** [comment]
@larismourullo certeza temos que dar uma "traduzida" para ensinar, mas ele serve como um ótimo referencial para a criação do conteúdo.
E sim, tem uma parte que foge de lógica, até pq lidar com arquivos é muito especifico de cada linguagem e framework.
É sempre importante incluir a bibliografia do curso tb.

**Comment by larismourullo** [comment]
@houstondapaz como eu disse eu senti que ele explicou CRUD de forma bem geral e meio voltado pra algoritmos já. Acho que isso pode entrar em um outro curso e a parte de estrutura de dados também. Porque estrutura de dados é BEEEEEEEEEEM COMPLEXO pra quem ta começando. E acho que por ser bem extenso mereça um curso só pra isso.

**Comment by oliveira-julio** [comment]
@larismourullo dá uma olhada no livro How to Design Programs( htdp), que tem como uma das propostas ser introdutório de programação. É bem didático, e usa o paradigma funcional (mesmo sem dizer que tá usando). A estrutura do livro também é bem interessante, tendo bastante exercícios para cada conceito apresentado. O livro foca tanto no ensino da teoria, quanto na produção de um bom código, mas de forma bem simples . Ele usa uma ideia chamada Design recipe que é uma grande ajuda para quem tá iniciando ( ou mesmo para quem já é familiarizado com programação).
Link: http://www.htdp.org/

**Comment by larismourullo** [comment]
@JulioOliveiraCosta vou olhar o livro logo mais, mas acredito que seja uma utilizarmos algumas coisas dele para o curso.

**Comment by houstondapaz** [comment]
Pessoal depois de ler o artigo sobre a adoção do [js nas materias introdutorias de stanford](https://imasters.com.br/desenvolvimento/por-que-stanford-trocou-java-por-javascript) acho que devemos seguir essa linha.
O que acham? (leiam o texto é muito bom)

**Comment by lukkaslt** [comment]
Fonte: Lógica de Programação. A Construção de Algoritmos e Estruturas de Dados (Português) Capa Comum – 25 mai 2005

por Andre Luis Forbellone (Autor), Henri Eberspacher (Autor)

**Comment by ghost** [comment]
Vou deixar algumas fontes de estudos que usei para meu aprendizado:
 
https://github.com/benoitvallon/computer-science-in-javascript
http://composingprograms.com/versions/v1/
http://inst.eecs.berkeley.edu/~cs61a/sp15/
http://introcs.cs.princeton.edu/python/home/
http://blog.benoitvallon.com/data-structures-in-javascript/data-structures-in-javascript/
https://www.youtube.com/watch?v=2Op3QLzMgSY&list=PLE18841CABEA24090
https://www.youtube.com/watch?v=FIUJd_ZFmGo&list=PL7BcsI5ueSNFPCEisbaoQ0kXIDX9rR5FF
http://wps.prenhall.com/br_ascencio_2/77/19865/5085525.cw/index.html
http://inst.eecs.berkeley.edu/~scheme/

**Comment by pglapds** [comment]
Pessoal, tenho um repositório original onde estou mostrando como criar e estudar a lógica de programação.  PS: Eu mostro algumas ideias e faço a gramática onde aquela resolução pode ser aplicada. Contudo, acredito que não é suficiente. Objetivo: Criar análises, soluções de lógica e estudos gerais sobre a criatividade. Referência: https://github.com/pglapds/pseudoalgoritms

**Comment by ghost** [comment]
Interessante.
